### ISSUE TITLE
安装后没反应

### ISSUE THREAD

**Issue by jdjfjdsfj** [Forfuture-h/penmod_install_for1.2.0#1]
安装后什么也没有发生，系统无任何变化，再运行就会：
Welcome to use PenMods!
Developer:  RedbeanW
Repo:       https://github.com/PenUniverse/Installer
Version:    1.1.0
adb.exe: no devices/emulators found
请将词典笔与电脑连接，并开启ADB调试。
请进入 [更多设置]->[关于]->[法律监管] 后快速连续点击5次屏幕即可打开ADB调试。
正在等待...13s
设备 2CA0800003412102 已连接
在安装程序运行过程中，请保持设备连接。
DictPen is unlocked.
Assertion Failed: 当前系统已安装PenMods，请先还原系统再执行安装。

**Comment by tofuture-1** [comment]
格式化之后再尝试安装看看

**Comment by jdjfjdsfj** [comment]
> 格式化之后再尝试安装看看

把笔格式化吗

**Comment by tofuture-1** [comment]
是的

**Comment by jdjfjdsfj** [comment]
格式化后再装也一样

> 是的

**Comment by tofuture-1** [comment]
你的翻译笔是什么版本

**Comment by jdjfjdsfj** [comment]
2.1.2

**Comment by tofuture-1** [comment]
![Screenshot_2024-08-06-10-04-23-090_com.github.android.jpg](https://github.com/user-attachments/assets/a1775ffe-6e67-40a4-aeec-b75590d31a74)

**Comment by tofuture-1** [comment]
用adb去翻译笔的这个目录删掉有关的东西试试

**Comment by jdjfjdsfj** [comment]
login with "adb shell auth" to continue.
有密码

**Comment by tofuture-1** [comment]
b站专栏刷满分版的教程上面给有![Screenshot_2024-08-06-10-28-27-703_tv.danmaku.bili.jpg](https://github.com/user-attachments/assets/4a00b805-e2cf-4a9f-a2db-a75e1e824290)

**Comment by jdjfjdsfj** [comment]
目录中没有这些东西

**Comment by tofuture-1** [comment]
截个图看看

**Comment by jdjfjdsfj** [comment]
![image](https://github.com/user-attachments/assets/84ba6230-e326-43ba-b403-1015e5366d24)

**Comment by tofuture-1** [comment]
你用cd..退到根目录，再cd进到那个目录，然后再ls试试

**Comment by jdjfjdsfj** [comment]
can't cd to /usr/bin/runDictPen，进不去

**Comment by tofuture-1** [comment]
你到根目录了吗

**Comment by jdjfjdsfj** [comment]
有的

**Comment by jdjfjdsfj** [comment]
能cd到/usr/bin/，但不能cd到/usr/bin/runDictPen

**Comment by tofuture-1** [comment]
你ls看看这个目录下有什么

**Comment by jdjfjdsfj** [comment]
[root@YoudaoDictionaryPen-102:/usr/bin]# ls
 TouchTest                            modetest
'['                                   monkey
'[['                                  mouse-dpi-tool
 adb_auth.sh                          mp3play.sh
 adbd                                 mpg123
 alsamixer                            mpg123-id3dump
 amixer                               mpg123-strip
 aplay                                mpi_dec_mt_test
 ar                                   mpi_dec_multi_test
 arecord                              mpi_dec_test
 aserver                              mpi_enc_multi_test
 auto_aging_test.sh                   mpi_enc_test
 awk                                  mpi_rc2_test
 b2sum                                mpi_rc_test
 banana                               mpi_test
 base32                               mpp_info_test
 base64                               mpris-proxy
 basename                             ms_print
 bccmd                                msleep
 bluealsa                             mtdev-test
 bluealsa-aplay                       mtp-server
 bluealsa-rfcomm                      nl
 bluemoon                             nmeter
 bluetoothctl                         nohup
 bluez5_utils_wifi_config.sh          nproc
 bt_init.sh                           nslookup
 bt_load_rtk_firmware                 numfmt
 bt_pcba_test                         od
 bt_realtek_hfp_accept                on_ac_power
 bt_realtek_hfp_hanup                 openvt
 bt_realtek_hfp_start                 out123
 bt_realtek_start                     par_mem
 btattach                             par_ops
 btmon                                passwd
 bunzip2                              paste
 bw_file_rd                           patch
 bw_mem                               pathchk
 bw_mmap_rd                           pcre2grep
 bw_pipe                              pcre2test
 bw_tcp                               pcregrep
 bw_unix                              pcretest
 bzcat                                perl
 callgrind_annotate                   perlbug
 callgrind_control                    perldoc
 camera_rkisp.sh                      perlivp
 cap_raw_pic.sh                       perlthanks
 cec-compliance                       pgrep
 cec-ctl                              pi_stress
 cec-follower                         piconv
 cg_annotate                          pinky
 cg_diff                              pip_stress
 cg_merge                             pkill
 chcon                                pl2pm
 check_ota_space                      play
 check_ota_version                    playback_dev_ctrl
 check_stop_input_deamon_times.sh     pm-is-supported
 check_updata_result                  pmap
 check_user_space.sh                  pmqtest
 chrt                                 pod2html
 chvt                                 pod2man
 ciptool                              pod2text
 cksum                                pod2usage
 clear                                podchecker
 clear_userdisk                       podselect
 cmp                                  pr
 comm                                 print_battery_info.sh
 config_img_info                      print_progress_mem_info.sh
 corelist                             printf
 coreutils                            procrank
 cpan                                 proptest
 create_udisk_img                     protoc
 crontab                              prove
 csplit                               pstree
 curl                                 ptar
 cut                                  ptardiff
 cx18-ctl                             ptargrep
 cyclictest                           ptsematest
 dbus-binding-tool                    ptx
 dbus-cleanup-sockets                 pwdx
 dbus-daemon                          qml
 dbus-launch                          qmlpreview
 dbus-monitor                         qmlscene
 dbus-run-session                     qmltestrunner
 dbus-send                            rctest
 dbus-test-tool                       rds-ctl
 dbus-update-activation-environment   readlink
 dbus-uuidgen                         realpath
 dbusxx-introspect                    reboot_test.sh
 dbusxx-xml2cpp                       rec
 dc                                   reconnect_saved_bt.sh
 ddcmon                               recovery_other_system
 deallocvt                            remount_diskpart
 decode-dimms                         renice
 decode-edid                          reset
 decode-vaio                          reset_input-event
 decode_tm6000                        resize
 dhd                                  revert_dhcpcd
 dhrystone                            rfcomm
 diff                                 rk_airkiss
 dig_headset_sevice                   rk_wifi_init
 dircolors                            rkbt
 dirname                              rkbtsource
 disk                                 rkbtsource_server
 dos2unix                             rkisp_demo
 du                                   rkupdate
 dvb-fe-tool                          rm_free.sh
 dvb-format-convert                   rt-migrate-test
 dvbv5-daemon                         rtk_hciattach
 dvbv5-scan                           rtlbtmp
 dvbv5-zap                            rtwpriv
 eject                                runCapFrame
 enc2xs                               runCapTools
 encguess                             runDictPen
 enough                               runRkbtServer
 env                                  runWpas
 eq_drc_process                       run_eq_drc_process
 evtest                               run_input_event_monitor
 expand                               run_screen_test.sh
 export_qtlib_to_mtp.sh               run_uevent_monitor
 export_udisk                         runcon
 expr                                 rz
 faad                                 safe_powerdown
 factor                               save_sys_cfg
 factory_clear                        sbcdec
 fallocate                            sbcenc
 fbdraw                               sbcinfo
 fbshow                               scp
 fc-cache                             screen_onoff
 fc-cat                               screen_switch
 fc-list                              screen_switch_drmmode
 fc-match                             screen_switch_nodrm
 fc-pattern                           sdpscanner
 fc-query                             sdptool
 fc-scan                              send_event
 fc-validate                          sendme
 ffmpeg                               seq
 ffprobe                              set_camera_crop.sh
 find                                 set_rk817_config
 flac                                 setkeycodes
 flock                                setsid
 flushdisk                            sftp
 fmt                                  sha1sum
 fold                                 sha224sum
 free                                 sha256sum
 fuser                                sha384sum
 gapplication                         sha3sum
 gatt-service                         sha512sum
 gatttool                             shasum
 gcore                                show_all_md5.sh
 gdb                                  show_pid_cpurate.sh
 gdbserver                            show_sysmem_status.sh
 gdbus                                shred
 gdk-pixbuf-csource                   shuf
 gdk-pixbuf-pixdata                   signaltest
 gdk-pixbuf-query-loaders             sigwaittest
 gdk-pixbuf-thumbnailer               smemcap
 get_img_info                         sort
 get_network_status                   sox
 get_pcba_version                     soxi
 get_usb_status                       splain
 gio                                  split
 gio-querymodules                     ssh
 glmarktest                           ssh-add
 glmarktest.sh                        ssh-agent
 gresource                            ssh-copy-id
 groups                               ssh-keygen
 grpc_csharp_plugin                   ssh-keyscan
 grpc_node_plugin                     sshd_sevice
 grpc_objective_c_plugin              ssid_change
 grpc_php_plugin                      ssl_client
 grpc_python_plugin                   start_logging
 grpc_ruby_plugin                     stat
 gsettings                            stdbuf
 gsnap                                strace
 gst-device-monitor-1.0               strace-log-merge
 gst-discoverer-1.0                   stream
 gst-inspect-1.0                      stress
 gst-launch-1.0                       stressapptest
 gst-play-1.0                         stressapptest_test.sh
 gst-stats-1.0                        strings
 gst-typefind-1.0                     sum
 gstplay.sh                           svc
 guardian                             svsematest
 guardian_run                         system_post_wakeup
 h2ph                                 system_sleep_wakeup
 h2xs                                 sz
 hackbench                            tac
 hciattach                            tail
 hciconfig                            tar_syslog
 hcidump                              taskset
 hcitool                              tee
 hcitop                               telnet
 head                                 test
 hello                                test_camera.sh
 hex2hcd                              test_glmark.sh
 hexdump                              test_video.sh
 hilink-server                        tftp
 hostapd_cli                          time
 hostid                               timeout
 id                                   timing_o
 input-event-daemon                   tlb
 input_subsytem_monitor               top
 install                              touchpad-edge-detector
 instmodsh                            tr
 io                                   traceroute
 ipcrm                                truncate
 ipcs                                 tsort
 iperf                                tty
 ir-ctl                               ubus
 ir-keytable                          udevadm
 ivtv-ctl                             ueventmon
 jshn                                 unexpand
 json_pp                              uniq
 kill_test.sh                         unix2dos
 killall                              unlink
 kms-steal-crtc                       unlzma
 kms-universal-planes                 unxz
 kmstest                              unzip
 l2ping                               update
 l2test                               update_engine
 lame                                 upower
 last                                 uptime
 lat_connect                          usbdevice
 lat_ctx                              usbenable
 lat_fcntl                            users
 lat_fifo                             uudecode
 lat_fs                               uuencode
 lat_http                             v4l2-compliance
 lat_mem_rd                           v4l2-ctl
 lat_mmap                             v4l2-sysfs-path
 lat_ops                              valgrind
 lat_pagefault                        valgrind-di-server
 lat_pipe                             valgrind-listener
 lat_proc                             vbltest
 lat_rpc                              vendor_storage
 lat_select                           vgdb
 lat_sem                              video_play_by_gst.sh
 lat_sig                              vpu_api_test
 lat_syscall                          w
 lat_tcp                              wakeuptest.sh
 lat_udp                              watch_ntpd.sh
 lat_unix                             wayland-scanner
 lat_unix_connect                     waylandtest.sh
 len_onoff.sh                         wc
 less                                 wcap-decode
 libevdev-tweak-device                weston
 libinput                             weston-calibrator
 libinput-debug-events                weston-debug
 libinput-list-devices                weston-info
 libnetcfg                            weston-screenshooter
 line                                 weston-simple-damage
 lmdd                                 weston-simple-dmabuf-egl
 lmhttp                               weston-simple-dmabuf-v4l
 load_sys_cfg                         weston-simple-egl
 lockfile-check                       weston-simple-shm
 lockfile-create                      weston-simple-touch
 lockfile-remove                      weston-terminal
 lockfile-touch                       weston-touch-calibrator
 logger                               wget
 logname                              whetstone
 loop_o                               which
 lrz                                  who
 lsof                                 whoami
 lspci                                wifi_ap6xxx_rftest.sh
 lsscsi                               wifi_start.sh
 lsusb                                wl
 lsz                                  worktime-server
 lzcat                                xargs
 lzma                                 xmlcatalog
 mail-lock                            xmllint
 mail-touchlock                       xmlwf
 mail-unlock                          xsubpp
 md5sum                               xxd
 media-ctl                            xz
 memsize                              xzcat
 memtester                            ydupdate_ab_ota
 merge_video.sh                       ydupdate_diff_ota
 mesg                                 yes
 metaflac                             yuyv2bmp
 mhz                                  zip
 microcom                             zipcloak
 minimad                              zipdetails
 mk_passwd                            zipnote
 mkfifo                               zipsplit
 modeprint
有runDictPen

**Comment by tofuture-1** [comment]
奇怪了，装了之后翻译笔的设置是完全没有变化是吗

**Comment by jdjfjdsfj** [comment]
是的

**Comment by tofuture-1** [comment]
你试试重新刷一个2.0.7再装看看

**Comment by tofuture-1** [comment]
我也没有什么比较好的解决办法，或者你进讨论组问问，之前原版的安装程序也有人碰到过这个问题

**Comment by jdjfjdsfj** [comment]
OK，那先关闭这个issues
